package lotto;

public enum Cmd {
    START_CMD,
    INPUT_MONEY,
    PRINT_NUMBEROFLOTTO,
    PRINT_LOTTO_NUMBER,
    PRINT_CORRECT_LOTTO_NUMBER,
    INPUT_CORRECT_LOTTO_NUMBER,
    PRINT_BONUS_NUMBER,
    INPUT_BONUS_NUMBER,
    RESULT
}
