package lotto.domain;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.IntStream;
import lotto.Util.RandomNumberUtil;
import lotto.view.InputView;

public class Lotto {
    // TODO : 로또 가격 상수를 다른 곳으로 옮기는 것 고려
    private static final int LOTTO_PRICE = 1000;
    private List<List<Integer>> autoGeneratedLottoNumberList;
    private final List<Integer> numbers;
    private int amountNumber;

    public Lotto(List<Integer> numbers) {
        validate(numbers);
        this.numbers = numbers;
    }

    public void setAmountNumber() {
        amountNumber = InputView.inputAmountView() / LOTTO_PRICE;
    }

    public void setClientLottoNumber() {

    }

    public void setAutoGeneratedLottoNumberList() {
        IntStream.range(0, amountNumber)
                .forEach(i -> autoGeneratedLottoNumberList.add(generateAutoLottoNumberList()));
    }

    private List<Integer> generateAutoLottoNumberList() {
        List<Integer> lottoNumberList = new ArrayList<>();

        RandomNumberUtil.generateRandomNumberList(lottoNumberList);
        return lottoNumberList;
    }

    private void validate(List<Integer> numbers) {
        if (numbers.size() != 6) {
            throw new IllegalArgumentException();
        }
    }
}
