package lotto.controller;

import java.util.List;
import lotto.constant.LottoRanking;
import lotto.generator.RandomUniqueListGenerator;
import lotto.model.Lotto;
import lotto.model.LottoGameManager;
import lotto.model.LottoOwner;
import lotto.model.LottoResult;
import lotto.model.PurchasePrice;
import lotto.model.WinningLotto;
import lotto.view.InputView;
import lotto.view.OutputView;

public class LottoController {
    private final InputView inputView = new InputView();
    private final OutputView outputView = new OutputView();

    public void run() {
        try {
            startLottoGame();
        } catch (IllegalArgumentException | IllegalStateException e) {
            outputView.printText(e.getMessage());
        }
    }

    private void startLottoGame() {
        LottoOwner lottoOwner = getLottoOwner();
        outputView.printLottosInfo(lottoOwner.getLottosInfo());

        WinningLotto winningLotto = WinningLotto.createWinningLotto(getWinningLotto(), getBonusNumber());
        LottoGameManager lottoGameManager = LottoGameManager.createGameManager(lottoOwner, winningLotto);
        lottoGameManager.matchLottosWithWinningLotto();

        printWinningStatistics(lottoGameManager);
        outputView.printRateOfReturn(lottoGameManager.getRateOfReturn());
    }

    private LottoOwner getLottoOwner() {
        PurchasePrice purchasePrice = getPurchasePrice();
        List<Lotto> randomLottos = Lotto.getAutoGeneratedLottos(purchasePrice, new RandomUniqueListGenerator());
        LottoResult lottoResult = LottoResult.createLottoResult(LottoRanking.convertValuesIntoCounters());
        return LottoOwner.createLottoOwner(purchasePrice, randomLottos, lottoResult);
    }

    private PurchasePrice getPurchasePrice() {
        outputView.printEnterPurchaseAmount();
        return PurchasePrice.createPurchase(inputView.getPurchaseAmount());
    }

    private Lotto getWinningLotto() {
        outputView.printEnterWinningNumbers();
        return Lotto.createLottoWithNumbers(inputView.getWinningNumbers());
    }

    private int getBonusNumber() {
        outputView.printEnterBonusNumber();
        return inputView.getBonusNumber();
    }

    private void printWinningStatistics(LottoGameManager lottoGameManager) {
        outputView.printStartMatchingWinningLotto();
        outputView.printWinningStatistics(lottoGameManager.getWinningStatistics());
    }
}
